### ISSUE TITLE
Add a LICENSE?

### ISSUE THREAD

**Issue by bhrutledge** [mikebarkmin/send-to-trello-firefox-extension#1]
Hi there! First, thanks for writing this. I've already found it useful just by loading it temporarily. I'd like to build on it, but some recent reading suggests that it's prudent to make sure an open-source license is in place. [GitHub has a built-in process for this](https://help.github.com/articles/adding-a-license-to-a-repository/). Or, if you like, I can submit a PR.

**Comment by mikebarkmin** [comment]
Hi, thanks for that!

I have committed a license.

**Comment by bhrutledge** [comment]
Thank you!
